# Form implementation generated from reading ui file 'MainTab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
from model import GLWidget
from PyQt6.QtGui import QPixmap

class Ui_Form(object):
    def setupUi(self, Form):
        
        #list of Ports for RX & TX combobox
        Ports = ["COM5","COM2","COM3","COM4","COM1","COM6","COM7","COM8","COM9","/dev/cu.usbserial-1120","/dev/cu.usbserial-120"]
        #list of Values of Baud Rate

        values = [115200,1200, 2400, 4800, 9600, 19200,38400, 57600,800 ,230400, 400000, 460800, 921600, 1000000, 2000000]
        
        Form.setObjectName("Form")
        Form.resize(1250, 910)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.BaudRateTX_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BaudRateTX_label.setFont(font)
        self.BaudRateTX_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.BaudRateTX_label.setMidLineWidth(0)
        self.BaudRateTX_label.setObjectName("BaudRateTX_label")
        self.BaudRateTX_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);
            padding: 2px; /* Add padding to simulate border */
        }
    """)
        self.gridLayout.addWidget(self.BaudRateTX_label, 0, 0, 1, 1)
        self.BaudRateTX_TextEdit = QtWidgets.QComboBox(parent=Form)
        self.BaudRateTX_TextEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.BaudRateTX_TextEdit.setObjectName("BaudRateTX_TextEdit")
        self.BaudRateTX_TextEdit.addItems([str(value) for value in values])
        self.BaudRateTX_TextEdit.setStyleSheet("""
        QComboBox  {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
        }
    """)
        self.gridLayout.addWidget(self.BaudRateTX_TextEdit, 0, 1, 1, 1)
        self.Model = GLWidget()
        self.Model.setMaximumSize(QtCore.QSize(16777215, 600))
        self.Model.setObjectName("Model_textEdit")

        self.gridLayout.addWidget(self.Model, 0, 3, 6, 3)
        self.SendingComPort_label = QtWidgets.QLabel(parent=Form)
        self.SendingComPort_label.setFont(font)
        self.SendingComPort_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.SendingComPort_label.setMidLineWidth(0)
        self.SendingComPort_label.setObjectName("SendingComPort_label")
        self.SendingComPort_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);
            padding: 2px; /* Add padding to simulate border */
        }
    """)
        self.gridLayout.addWidget(self.SendingComPort_label, 1, 0, 1, 1)
        self.SendingComPort_comboBox = QtWidgets.QComboBox(parent=Form)
        self.SendingComPort_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.SendingComPort_comboBox.setObjectName("SendingComPort_comboBox")
        self.SendingComPort_comboBox.addItems(Ports)
        self.SendingComPort_comboBox.setStyleSheet("""
        QComboBox  {
            background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
        }
    """)
        self.gridLayout.addWidget(self.SendingComPort_comboBox, 1, 1, 1, 1)
        self.Sending_Connect_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Sending_Connect_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Sending_Connect_pushButton.setObjectName("Sending_Connect_pushButton")
        self.Sending_Connect_pushButton.setStyleSheet("""
        QPushButton {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
            border-radius: 10px; /* Rounded border */                                            
        }
        QPushButton:hover {
            background-color: green; /* Change the background color on hover */
            color: rgb(0, 0, 0); /* Change the font color on hover */
            border-color: rgb(255, 255, 255); /* Change the border color on hover */
                                                      
        }
    """)
        self.gridLayout.addWidget(self.Sending_Connect_pushButton, 2, 0, 1, 1)
        self.Sending_Disconnect_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Sending_Disconnect_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Sending_Disconnect_pushButton.setObjectName("Sending_Disconnect_pushButton")
        self.Sending_Disconnect_pushButton.setStyleSheet("""
        QPushButton {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
            border-radius: 10px; /* Rounded border */                                                   
        }
        QPushButton:hover {
            background-color: red; /* Change the background color on hover */
            color: rgb(0, 0, 0); /* Change the font color on hover */
            border-color: rgb(255, 255, 255); /* Change the border color on hover */
                                                      
        }
    """)
        self.gridLayout.addWidget(self.Sending_Disconnect_pushButton, 2, 1, 1, 1)
        self.BaudRateRX_label = QtWidgets.QLabel(parent=Form)
        self.BaudRateRX_label.setFont(font)
        self.BaudRateRX_label.setObjectName("BaudRateRX_label")
        self.BaudRateRX_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
        self.gridLayout.addWidget(self.BaudRateRX_label, 3, 0, 1, 1)
        self.BaudRateRX_TextEdit = QtWidgets.QComboBox(parent=Form)
        self.BaudRateRX_TextEdit.setMaximumSize(QtCore.QSize(250, 30))
        self.BaudRateRX_TextEdit.setObjectName("BaudRateRX_TextEdit")
        self.BaudRateRX_TextEdit.addItems([str(value) for value in values])
        self.BaudRateRX_TextEdit.setStyleSheet("""
        QComboBox  {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
        }
    """)
        
        self.gridLayout.addWidget(self.BaudRateRX_TextEdit, 3, 1, 1, 1)
        self.ReceivingComPort_label = QtWidgets.QLabel(parent=Form)
        self.ReceivingComPort_label.setFont(font)
        self.ReceivingComPort_label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ReceivingComPort_label.setMidLineWidth(0)
        self.ReceivingComPort_label.setObjectName("ReceivingComPort_label")
        self.ReceivingComPort_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
        
        self.gridLayout.addWidget(self.ReceivingComPort_label, 4, 0, 1, 1)
        self.ReceivingComPort_comboBox = QtWidgets.QComboBox(parent=Form)
        self.ReceivingComPort_comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.ReceivingComPort_comboBox.setObjectName("ReceivingComPort_comboBox")
        self.ReceivingComPort_comboBox.addItems(Ports) 
        self.ReceivingComPort_comboBox.setStyleSheet("""
        QComboBox  {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
        }
    """)
        self.gridLayout.addWidget(self.ReceivingComPort_comboBox, 4, 1, 1, 1)
        self.ReceivingTerminal_label = QtWidgets.QLabel(parent=Form)
        self.ReceivingTerminal_label.setFont(font)
        self.ReceivingTerminal_label.setObjectName("ReceivingTerminal_label")
        self.ReceivingTerminal_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
         
        self.gridLayout.addWidget(self.ReceivingTerminal_label, 5, 0, 1, 1)
        self.ReceivingWindow_textEdit = QtWidgets.QTextEdit(parent=Form)
        self.ReceivingWindow_textEdit.setMaximumSize(QtCore.QSize(250, 200))
        self.ReceivingWindow_textEdit.setReadOnly(True)
        self.ReceivingWindow_textEdit.setObjectName("ReceivingWindow_textEdit")
        self.ReceivingWindow_textEdit.setStyleSheet("""
        QTextEdit {
            background-color: #333333;                                        
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);                                         
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
        self.gridLayout.addWidget(self.ReceivingWindow_textEdit, 5, 1, 1, 1)
        self.LOGO_label= QtWidgets.QLabel(parent=Form)
        LOGO_file_path =  QPixmap("images/SwiftACT LOGO.png")
        self.LOGO_label.setPixmap(LOGO_file_path)
        self.LOGO_label.setMaximumSize(QtCore.QSize(600, 400))
        self.gridLayout.addWidget(self.LOGO_label,5,2,1,1)
        self.Receiving_Connect_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Receiving_Connect_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Receiving_Connect_pushButton.setObjectName("Receiving_Connect_pushButton")
        self.Receiving_Connect_pushButton.setStyleSheet("""
        QPushButton {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
            border-radius: 10px; /* Rounded border */                                                      
        }
        QPushButton:hover {
            background-color: green; /* Change the background color on hover */
            color: rgb(0, 0, 0); /* Change the font color on hover */
            border-color: rgb(255, 255, 255); /* Change the border color on hover */
                                                      
        }
    """)
        self.gridLayout.addWidget(self.Receiving_Connect_pushButton, 6, 0, 1, 1)
        self.Receiving_Disconnect_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Receiving_Disconnect_pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Receiving_Disconnect_pushButton.setObjectName("Receiving_Disconnect_pushButton")
        self.Receiving_Disconnect_pushButton.setStyleSheet("""
        QPushButton {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
            border-radius: 10px; /* Rounded border */                                                 
        }
        QPushButton:hover {
            background-color: red; /* Change the background color on hover */
            color: rgb(0, 0, 0); /* Change the font color on hover */
            border-color: rgb(255, 255, 255); /* Change the border color on hover */
                                                      
        }
    """)
        self.gridLayout.addWidget(self.Receiving_Disconnect_pushButton, 6, 1, 1, 1)
        self.Time_label = QtWidgets.QLabel(parent=Form)
        self.Time_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.Time_label.setFont(font)
        self.Time_label.setToolTipDuration(-10)
        self.Time_label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.Time_label.setObjectName("Time_label")
        self.Time_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);                            
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
        self.gridLayout.addWidget(self.Time_label, 6, 2, 1, 1)
        self.Time_LineEdit = QtWidgets.QLineEdit(parent=Form)
        self.Time_LineEdit.setMaximumSize(QtCore.QSize(250, 16777215))
        self.Time_LineEdit.setReadOnly(True)
        self.Time_LineEdit.setObjectName("Time_LineEdit")
        self.Time_LineEdit.setStyleSheet("""
        QLineEdit {
            background-color: #333333;                                        
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);   
            border-radius: 10px; /* Rounded border */                              
            padding: 2px; /* Add padding to simulate border */
        }
    """) 
        self.gridLayout.addWidget(self.Time_LineEdit, 6, 3, 1, 1)
        self.position_label = QtWidgets.QLabel(parent=Form)
        self.position_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.position_label.setFont(font)
        self.position_label.setToolTipDuration(-10)
        self.position_label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.position_label.setObjectName("position_label")
        self.position_label.setStyleSheet("""
        QLabel {
            color: rgb(64, 224, 208);                            
            padding: 2px; /* Add padding to simulate border */
        }
    """)  
        self.gridLayout.addWidget(self.position_label, 6, 4, 1, 1)
        self.position_Pushbutton = QtWidgets.QPushButton(parent=Form)
        self.position_Pushbutton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.position_Pushbutton.setObjectName("position_Pushbutton")
        self.position_Pushbutton.setStyleSheet("""
        QPushButton {
           background-color: #333333;
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
            border-radius: 10px; /* Rounded border */                                   
        }
        QPushButton:hover {
            background-color: green; /* Change the background color on hover */
            color: rgb(0, 0, 0); /* Change the font color on hover */
            border-color: rgb(255, 255, 255); /* Change the border color on hover */
                                                      
        }
    """)
        self.gridLayout.addWidget(self.position_Pushbutton, 6, 5, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MainBatteryStatus_groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.MainBatteryStatus_groupBox_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.MainBatteryStatus_groupBox_3.setFont(font)
        self.MainBatteryStatus_groupBox_3.setObjectName("MainBatteryStatus_groupBox_3")
        self.MainBatteryStatus_groupBox_3.setStyleSheet("""
        QGroupBox {
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
                                                                                                
        }
        QLabel {
            color: rgb(64, 224, 208);                            
            padding: 2px; /* Add padding to simulate border */
        }
        QLineEdit {
            background-color: #333333;                                        
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);   
             border-radius: 10px;
        }
                                                        
    """)  
        self.BatteryVolt_label_3 = QtWidgets.QLabel(parent=self.MainBatteryStatus_groupBox_3)
        self.BatteryVolt_label_3.setGeometry(QtCore.QRect(10, 60, 80, 35))
        self.BatteryVolt_label_3.setFont(font)
        self.BatteryVolt_label_3.setObjectName("BatteryVolt_label_3")
        self.BatteryVolt_LineEdit_3 = QtWidgets.QLineEdit(parent=self.MainBatteryStatus_groupBox_3)
        self.BatteryVolt_LineEdit_3.setGeometry(QtCore.QRect(130, 60, 241, 22))
        self.BatteryVolt_LineEdit_3.setReadOnly(True)
        self.BatteryVolt_LineEdit_3.setObjectName("BatteryVolt_LineEdit_3")
        self.Current_label_3 = QtWidgets.QLabel(parent=self.MainBatteryStatus_groupBox_3)
        self.Current_label_3.setGeometry(QtCore.QRect(10, 120, 80, 35))
        self.Current_label_3.setFont(font)
        self.Current_label_3.setObjectName("Current_label_3")
        self.Current33_label_3 = QtWidgets.QLabel(parent=self.MainBatteryStatus_groupBox_3)
        self.Current33_label_3.setGeometry(QtCore.QRect(10, 180, 110, 35))
        self.Current33_label_3.setFont(font)
        self.Current33_label_3.setObjectName("Current33_label_3")
        self.Current5_label_3 = QtWidgets.QLabel(parent=self.MainBatteryStatus_groupBox_3)
        self.Current5_label_3.setGeometry(QtCore.QRect(10, 240, 100, 35))
        self.Current5_label_3.setFont(font)
        self.Current5_label_3.setObjectName("Current5_label_3")
        self.Current_LineEdit_3 = QtWidgets.QLineEdit(parent=self.MainBatteryStatus_groupBox_3)
        self.Current_LineEdit_3.setGeometry(QtCore.QRect(130, 120, 241, 22))
        self.Current_LineEdit_3.setReadOnly(True)
        self.Current_LineEdit_3.setObjectName("Current_LineEdit_3")
        self.Current33_LineEdit_3 = QtWidgets.QLineEdit(parent=self.MainBatteryStatus_groupBox_3)
        self.Current33_LineEdit_3.setGeometry(QtCore.QRect(130, 180, 241, 22))
        self.Current33_LineEdit_3.setReadOnly(True)
        self.Current33_LineEdit_3.setObjectName("Current33_LineEdit_3")
        self.Current5_LineEdit_3 = QtWidgets.QLineEdit(parent=self.MainBatteryStatus_groupBox_3)
        self.Current5_LineEdit_3.setGeometry(QtCore.QRect(130, 240, 241, 22))
        self.Current5_LineEdit_3.setReadOnly(True)
        self.Current5_LineEdit_3.setObjectName("Current5_LineEdit_3")
        self.horizontalLayout_3.addWidget(self.MainBatteryStatus_groupBox_3)
        self.SubsystemStatus_groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.SubsystemStatus_groupBox_3.setEnabled(True)
        self.SubsystemStatus_groupBox_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.SubsystemStatus_groupBox_3.setFont(font)
        self.SubsystemStatus_groupBox_3.setObjectName("SubsystemStatus_groupBox_3")
        self.SubsystemStatus_groupBox_3.setStyleSheet("""
        QGroupBox {
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
                                                                                                
        }
        QLabel {
            color: rgb(64, 224, 208);                            
            padding: 2px; /* Add padding to simulate border */
        }
        QLineEdit {
            background-color: #333333;                                        
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);   
             border-radius: 10px;
        }
                                                        
    """)  
        self.OBCStatus_label_3 = QtWidgets.QLabel(parent=self.SubsystemStatus_groupBox_3)
        self.OBCStatus_label_3.setGeometry(QtCore.QRect(10, 60, 100, 35))
        self.OBCStatus_label_3.setFont(font)
        self.OBCStatus_label_3.setObjectName("OBCStatus_label_3")
        self.ADCSStatus_label_3 = QtWidgets.QLabel(parent=self.SubsystemStatus_groupBox_3)
        self.ADCSStatus_label_3.setGeometry(QtCore.QRect(10, 120, 111, 35))
        self.ADCSStatus_label_3.setFont(font)
        self.ADCSStatus_label_3.setObjectName("ADCSStatus_label_3")
        self.PayloadStatus_label_3 = QtWidgets.QLabel(parent=self.SubsystemStatus_groupBox_3)
        self.PayloadStatus_label_3.setGeometry(QtCore.QRect(10, 180, 132, 35))
        self.PayloadStatus_label_3.setFont(font)
        self.PayloadStatus_label_3.setObjectName("PayloadStatus_label_3")
        self.CommAntennaStatus_label_3 = QtWidgets.QLabel(parent=self.SubsystemStatus_groupBox_3)
        self.CommAntennaStatus_label_3.setGeometry(QtCore.QRect(10, 240, 151, 35))
        self.CommAntennaStatus_label_3.setFont(font)
        self.CommAntennaStatus_label_3.setObjectName("CommAntennaStatus_label_3")
        self.Payload_LineEdit_3 = QtWidgets.QLineEdit(parent=self.SubsystemStatus_groupBox_3)
        self.Payload_LineEdit_3.setGeometry(QtCore.QRect(160, 180, 211, 22))
        self.Payload_LineEdit_3.setReadOnly(True)
        self.Payload_LineEdit_3.setObjectName("Payload_LineEdit_3")
        self.ADCS_LineEdit_3 = QtWidgets.QLineEdit(parent=self.SubsystemStatus_groupBox_3)
        self.ADCS_LineEdit_3.setGeometry(QtCore.QRect(160, 120, 211, 22))
        self.ADCS_LineEdit_3.setReadOnly(True)
        self.ADCS_LineEdit_3.setObjectName("ADCS_LineEdit_3")
        self.AntennaStatus_LineEdit_3 = QtWidgets.QLineEdit(parent=self.SubsystemStatus_groupBox_3)
        self.AntennaStatus_LineEdit_3.setGeometry(QtCore.QRect(160, 240, 211, 22))
        self.AntennaStatus_LineEdit_3.setReadOnly(True)
        self.AntennaStatus_LineEdit_3.setObjectName("AntennaStatus_LineEdit_3")
        self.OBC_LineEdit_3 = QtWidgets.QLineEdit(parent=self.SubsystemStatus_groupBox_3)
        self.OBC_LineEdit_3.setGeometry(QtCore.QRect(160, 60, 211, 22))
        self.OBC_LineEdit_3.setReadOnly(True)
        self.OBC_LineEdit_3.setObjectName("OBC_LineEdit_3")
        self.horizontalLayout_3.addWidget(self.SubsystemStatus_groupBox_3)
        self.ExternalSystemStatus_groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.ExternalSystemStatus_groupBox_3.setStyleSheet("""
        QGroupBox {
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);
                                                                                                
        }
        QLabel {
            color: rgb(64, 224, 208);                            
        }
        QLineEdit {
            background-color: #333333;                                        
            color: rgb(64, 224, 208);
            border: 2px solid rgb(64, 224, 208);   
            border-radius: 10px;
        }                                                   
                                                        
    """)  
        self.ExternalSystemStatus_groupBox_3.setMaximumSize(QtCore.QSize(16777215, 300))
        self.ExternalSystemStatus_groupBox_3.setFont(font)
        self.ExternalSystemStatus_groupBox_3.setObjectName("ExternalSystemStatus_groupBox_3")
        self.TempSensorStatus_label_3 = QtWidgets.QLabel(parent=self.ExternalSystemStatus_groupBox_3)
        self.TempSensorStatus_label_3.setGeometry(QtCore.QRect(10, 50, 121, 35))
        self.TempSensorStatus_label_3.setFont(font)
        self.TempSensorStatus_label_3.setObjectName("TempSensorStatus_label_3")
        self.SolarStatus3_label_3 = QtWidgets.QLabel(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus3_label_3.setGeometry(QtCore.QRect(10, 200, 124, 35))
        self.SolarStatus3_label_3.setFont(font)
        self.SolarStatus3_label_3.setObjectName("SolarStatus3_label_3")
        self.SolarStatus2_label_3 = QtWidgets.QLabel(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus2_label_3.setGeometry(QtCore.QRect(10, 150, 124, 35))
        self.SolarStatus2_label_3.setFont(font)
        self.SolarStatus2_label_3.setObjectName("SolarStatus2_label_3")
        self.SolarStatus1_label_3 = QtWidgets.QLabel(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus1_label_3.setGeometry(QtCore.QRect(10, 100, 124, 35))
        self.SolarStatus1_label_3.setFont(font)
        self.SolarStatus1_label_3.setObjectName("SolarStatus1_label_3")
        self.SolarStatus4_label_4 = QtWidgets.QLabel(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus4_label_4.setGeometry(QtCore.QRect(10, 250, 101, 35))
        self.SolarStatus4_label_4.setFont(font)
        self.SolarStatus4_label_4.setObjectName("SolarStatus4_label_4")
        self.SolarStatus4_LineEdit_3 = QtWidgets.QLineEdit(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus4_LineEdit_3.setGeometry(QtCore.QRect(150, 250, 221, 22))
        self.SolarStatus4_LineEdit_3.setReadOnly(True)
        self.SolarStatus4_LineEdit_3.setObjectName("SolarStatus4_LineEdit_3")
        self.SolarStatus3_LineEdit_3 = QtWidgets.QLineEdit(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus3_LineEdit_3.setGeometry(QtCore.QRect(150, 200, 221, 22))
        self.SolarStatus3_LineEdit_3.setReadOnly(True)
        self.SolarStatus3_LineEdit_3.setObjectName("SolarStatus3_LineEdit_3")
        self.SolarStatus2_LineEdit_3 = QtWidgets.QLineEdit(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus2_LineEdit_3.setGeometry(QtCore.QRect(150, 150, 221, 22))
        self.SolarStatus2_LineEdit_3.setReadOnly(True)
        self.SolarStatus2_LineEdit_3.setObjectName("SolarStatus2_LineEdit_3")
        self.SolarStatus1_LineEdit_3 = QtWidgets.QLineEdit(parent=self.ExternalSystemStatus_groupBox_3)
        self.SolarStatus1_LineEdit_3.setGeometry(QtCore.QRect(150, 100, 221, 22))
        self.SolarStatus1_LineEdit_3.setReadOnly(True)
        self.SolarStatus1_LineEdit_3.setObjectName("SolarStatus1_LineEdit_3")
        self.TempSensorStatus_LineEdit_3 = QtWidgets.QLineEdit(parent=self.ExternalSystemStatus_groupBox_3)
        self.TempSensorStatus_LineEdit_3.setGeometry(QtCore.QRect(150, 50, 221, 22))
        self.TempSensorStatus_LineEdit_3.setReadOnly(True)
        self.TempSensorStatus_LineEdit_3.setObjectName("TempSensorStatus_LineEdit_3")
        self.horizontalLayout_3.addWidget(self.ExternalSystemStatus_groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 0, 1, 6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BaudRateTX_label.setText(_translate("Form", "Baud Rate TX"))
        self.SendingComPort_label.setText(_translate("Form", "Send COM PORT"))
        self.Sending_Connect_pushButton.setText(_translate("Form", "Connect"))
        self.Sending_Disconnect_pushButton.setText(_translate("Form", "Disconnect"))
        self.BaudRateRX_label.setText(_translate("Form", "Baud Rate RX"))
        self.ReceivingComPort_label.setText(_translate("Form", "Receiving COM PORT"))
        self.ReceivingTerminal_label.setText(_translate("Form", "Receiving Terminal"))
        self.Receiving_Connect_pushButton.setText(_translate("Form", "Connect"))
        self.Receiving_Disconnect_pushButton.setText(_translate("Form", "Disconnect"))
        self.Time_label.setText(_translate("Form", "Time"))
        self.position_label.setText(_translate("Form", "Position"))
        self.position_Pushbutton.setText(_translate("Form", "Click here"))
        self.MainBatteryStatus_groupBox_3.setTitle(_translate("Form", "Main Battery Status"))
        self.BatteryVolt_label_3.setText(_translate("Form", "Voltage"))
        self.Current_label_3.setText(_translate("Form", "Current"))
        self.Current33_label_3.setText(_translate("Form", "Current 3.3"))
        self.Current5_label_3.setText(_translate("Form", "Current 5"))
        self.SubsystemStatus_groupBox_3.setTitle(_translate("Form", "Subsystem Status"))
        self.OBCStatus_label_3.setText(_translate("Form", "OBC"))
        self.ADCSStatus_label_3.setText(_translate("Form", "ADCS"))
        self.PayloadStatus_label_3.setText(_translate("Form", "Payload"))
        self.CommAntennaStatus_label_3.setText(_translate("Form", "Comm Antenna"))
        self.ExternalSystemStatus_groupBox_3.setTitle(_translate("Form", "External System Status"))
        self.TempSensorStatus_label_3.setText(_translate("Form", "Temp Sensor"))
        self.SolarStatus3_label_3.setText(_translate("Form", "Solar 3"))
        self.SolarStatus2_label_3.setText(_translate("Form", "Solar 2"))
        self.SolarStatus1_label_3.setText(_translate("Form", "Solar 1"))
        self.SolarStatus4_label_4.setText(_translate("Form", "Solar 4"))
